// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApi.Infrastructure;

#nullable disable

namespace ProductApi.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductApi.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phones, laptops, and gadgets",
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Apparel and accessories",
                            Name = "Clothing",
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Furniture, appliances, and kitchenware",
                            Name = "Home & Kitchen",
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fiction, non-fiction, and educational titles",
                            Name = "Books",
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProductApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic wireless mouse with USB receiver",
                            ImageUrl = "https://example.com/images/mouse.jpg",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 19.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RGB backlit mechanical keyboard, blue switches",
                            ImageUrl = "https://example.com/images/keyboard.jpg",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 59.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IPS panel monitor with HDR support",
                            ImageUrl = "https://example.com/images/monitor.jpg",
                            IsActive = true,
                            Name = "27-inch 4K Monitor",
                            Price = 329.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-in-1 USB-C hub with HDMI and SD card reader",
                            ImageUrl = "https://example.com/images/usbhub.jpg",
                            IsActive = true,
                            Name = "USB-C Hub",
                            Price = 34.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plain white cotton t-shirt, unisex fit",
                            ImageUrl = "https://example.com/images/tshirt.jpg",
                            IsActive = true,
                            Name = "Cotton T-Shirt",
                            Price = 9.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic blue denim jacket, mid-weight",
                            ImageUrl = "https://example.com/images/jacket.jpg",
                            IsActive = true,
                            Name = "Denim Jacket",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight running shoes with cushioned sole",
                            ImageUrl = "https://example.com/images/shoes.jpg",
                            IsActive = true,
                            Name = "Running Shoes",
                            Price = 74.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10-piece cookware set, dishwasher safe",
                            ImageUrl = "https://example.com/images/cookware.jpg",
                            IsActive = true,
                            Name = "Stainless Steel Cookware Set",
                            Price = 129.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smart robot vacuum with app control",
                            ImageUrl = "https://example.com/images/vacuum.jpg",
                            IsActive = true,
                            Name = "Robot Vacuum Cleaner",
                            Price = 199.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A Handbook of Agile Software Craftsmanship",
                            ImageUrl = "https://example.com/images/cleancode.jpg",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 39.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Your journey to mastery, 20th anniversary edition",
                            ImageUrl = "https://example.com/images/pragprog.jpg",
                            IsActive = true,
                            Name = "The Pragmatic Programmer",
                            Price = 44.99m,
                            UpdatedAt = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProductApi.Models.Product", b =>
                {
                    b.HasOne("ProductApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
