name: Deploy Auth Service

on:
  push:
    branches:
      - Dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish Auth
        run: dotnet publish AuthApi/AuthApi.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth
          path: ./publish

  # deploy:
  #   runs-on: windows-latest
  #   needs: build

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: auth

  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: 'ECommerce-Auth-Service'
  #         publish-profile: ${{ secrets.AUTH_PUBLISH_PROFILE }}
  #         package: .
