name: .NET CI + CD

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - Dev
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files (debug)
        run: ls -R

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore E_Commerce.slnx

      - name: Build solution
        run: dotnet build E_Commerce.slnx --no-restore --configuration Release

      - name: Run AuthApi tests
        run: dotnet test Auth.Test/Auth.Test.csproj --configuration Release --no-build

  
