name: Deploy Product Service

on:
  push:
    branches:
      - Dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish Product
        run: dotnet publish ProductApi/ProductApi.csproj -c Release -o ./publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: product-artifact
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Build Artifac
        uses: actions/download-artifact@v4
        with:
          name: product

      - name: Deploy to Azure Product Api
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Product-Service'
          publish-profile: ${{ secrets.PRODUCT_PUBLISH_PROFILE }}
          package: .